### PR TITLE
chinese version

### PR DESCRIPTION
**Pull request by 496080199**
hi! I added chinese version,can you merge?But I can't use min.js generated by some online tools, can you help with it?

### CODE REVIEW

**Comment by martinlsanchez** [comment]
Hi, 
Thx for your PR, for sure I will take a look at the code when you finish it.
I usually use: https://www.minifier.org/ for CSS and JS files.

Please add a commit using minified files to keeper performance :+1: 
You always test it agains: [Google Page Speed](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fdaiauctions.com%2F&tab=desktop)

Looking forward to your code, I push some fixes this weekend so make sure you pull the latest code. :)

**Comment by 496080199** [comment]
Hi.I have minified the js files,and run it at [Google PageSpeed](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fdaiauctions.xiaopao.gq%2F).
Is this OK?

**Comment by martinlsanchez** [comment]
I will try to take a look at it tomorrow or fore sure this weekend.

I really glad that you took the time to make this contribution. :1st_place_medal: 
Was not in my mind roadmap for this project but I love it!

:-)

**Comment by martinlsanchez** [comment]
Wow! Awesome job, I tested it today and can't wait to put it online. 👍 

I have a only a few concerns to resolve. 
You based your `zh/flap.html` and `zh/flap.js` from the version 1.2.17 and the latest one is 1.3.3. It's only 3 commits back so would be great if you can update it.

The new stuff, it's only two new boxes at the top (MKR Price and Glossary Link) and some text at the footer to support load all history events.

You will find all the code than you need, implemented and working in the English version. :-)

Could you send me a private message in tweeter to get in touch about some translations?

**Comment by 496080199** [comment]
Hello! I am very glad to accept your opinion, I have updated the code of the zh directory to the latest. But I don't think the current update method is very good, maybe try to quote i18n to support multiple languages, but I'm not very professional. Finally, I cannot use Twitter here, I'm very sorry.

**Comment by martinlsanchez** [comment]
Yep, I agree than the current language support right now is far from ideal and i18n is the way to go..... 

But Like I told, your contribution surprise me :-) and I didn't want to leave you hanging with your PR.... so I can temporally support the current two languages bad implementation. Sure I gonna update it soon.

sooooooo, I gonna merge you code!!! 👍 . Make some tweaks and try to deploy it today.

Is there any way than I can contact you? email maybe?

**Pull request merged**
